[tool.poetry]
name = "module06"
version = "0.1.0"
description = "Module 06"
authors = ["777fesenko.d@gmail.com"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"
faker = "^19.3.0"
